[server]
headless = true
fileWatcherType = "none"
runOnSave = false
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#00e5ff"
backgroundColor = "#050b14"
secondaryBackgroundColor = "#0a192f"
textColor = "#f8fafc"
font = "sans serif"
